version: "3"
services:
  authdb:
    image: postgres
    container_name: authPG
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    image: auth-service:dev
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - "E:/development/cg/full_stack/auth-service:/usr/src/app"
      - /usr/src/app/node_modules
    ports:
      - "5501:5501"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - authdb
    stdin_open: true
    tty: true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:
    external: true
